# Generated by Django 3.0.7 on 2020-07-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0006_artical_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical_m',
            name='In_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artical_m',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artical_m',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
