# Generated by Django 3.0.7 on 2020-07-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0008_auto_20200713_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical_m',
            name='creater',
        ),
    ]
