# Generated by Django 3.0.7 on 2020-07-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0013_auto_20200724_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical_m',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
