# Generated by Django 3.0.7 on 2020-06-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0002_auto_20200630_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='head',
            old_name='header',
            new_name='txt',
        ),
    ]
