# Generated by Django 3.0.7 on 2020-06-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0003_auto_20200630_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contents',
            options={'verbose_name_plural': 'contente'},
        ),
    ]
