# Generated by Django 3.0.7 on 2020-07-14 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artical', '0009_remove_artical_m_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical_m',
            name='creater',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
